# Generated by Django 6.0.4 on 2026-04-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('router_id', models.CharField(max_length=20, unique=True)),
                ('protocol', models.CharField(choices=[('ospf', 'OSPF'), ('bgp', 'BGP'), ('both', 'Both')], default='ospf', max_length=10)),
                ('as_number', models.IntegerField(blank=True, null=True)),
                ('ospf_area', models.CharField(blank=True, max_length=20, null=True)),
                ('x_pos', models.IntegerField(default=200)),
                ('y_pos', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('ospf', 'OSPF'), ('bgp', 'BGP'), ('system', 'System')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BGPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('ebgp', 'eBGP'), ('ibgp', 'iBGP')], max_length=10)),
                ('is_established', models.BooleanField(default=True)),
                ('local_performance', models.IntegerField(default=100)),
                ('med', models.IntegerField(default=0)),
                ('local_router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_local', to='simulator.router')),
                ('peer_router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_peer', to='simulator.router')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=10)),
                ('bandwidth', models.IntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_form', to='simulator.router')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='simulator.router')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
