# Generated by Django 6.0.4 on 2026-04-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgpsession',
            old_name='local_performance',
            new_name='local_preference',
        ),
    ]
